// Tauri 2.0 plugins must declare their commands via tauri-plugin's build helper
// so the capability system can validate them. This also generates the
// autogenerated permission files under `permissions/autogenerated/`.

const COMMANDS: &[&str] = &[
    "register_bridge",
    "relay_result",
    "relay_event",
    "proxy_url",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
